# Build Java apps
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      echo Starting the build...
      jshell https://bit.ly/make-java
    displayName: 'Build with Make.java...'
