jdk: openjdk11

install:
  - cp mainrunner.properties build.properties
  - VERSION="2-SNAPSHOT"
  - jshell https://bit.ly/make-java
  - mvn install:install-file -DgroupId=de.sormuras.mainrunner -DartifactId=mainrunner-engine -Dversion=${VERSION} -Dpackaging=jar -DgeneratePom=true -Dfile=target/main/modules/de.sormuras.mainrunner.engine-${VERSION}.jar -Dsources=target/main/sources/de.sormuras.mainrunner.engine-${VERSION}-sources.jar -Djavadoc=target/main/javadoc/mainrunner-${VERSION}-javadoc.jar
