name: CI
on: push
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build mainrunner'
        run: jshell build.jsh
      - name: 'Install modules into local Maven repository'
        run: source src/build/maven/install.sh
      - name: 'Build again using no-installation Bach.java'
        run: jshell https://bit.ly/bach-jsh
#      - name: 'Install modules into local Maven repository, again'
#        run: source bin/maven-install.sh
