name: CI
on: push
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build mainrunner'
        run: jshell https://bit.ly/bach-jsh
      - name: 'Install modules into local Maven repository'
        run: |
          BACH="java --module-path .bach/build/lib --module de.sormuras.bach"
          INSTALL="--batch-mode --no-transfer-progress install:install-file"
          ${BACH} tool mvn ${INSTALL} @.bach/out/main/deploy/de.sormuras.mainrunner.api/maven-cli-arguments.txt
          ${BACH} tool mvn ${INSTALL} @.bach/out/main/deploy/de.sormuras.mainrunner.engine/maven-cli-arguments.txt
