name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      sha7: ${{ steps.version.outputs.sha7 }}
      sha8: ${{ steps.version.outputs.sha8 }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: 'Compute short version strings'
        id: version
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          SHA8=$(echo "${{ github.sha }}" | cut -c1-8)
          echo "::set-output name=sha7::${SHA7}"
          echo "::set-output name=sha7::${SHA8}"
          echo "::set-output name=version::2.2-ea+${SHA7}"

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea
      - name: 'Build Mainrunner ${{ needs.setup.outputs.version }} with Bach'
        uses: sormuras/bach-build@main
        with:
          project-version: ${{ needs.setup.outputs.version }}
          project-main-jarslug: 'early-access'
      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ needs.setup.outputs.version }}
          path: |
            LICENSE
            .bach/workspace/logbook.md
            .bach/workspace/documentation/api
            .bach/workspace/modules

  deploy-modules:
    needs: [ setup, build ]
    if: github.event_name == 'push' && github.repository == 'sormuras/mainrunner' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download build artifact ${{ needs.setup.outputs.version }}'
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ needs.setup.outputs.version }}
      - name: 'Release early-access build to https://github.com/sormuras/mainrunner/releases/tag/early-access'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'early-access'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: 'Mainrunner ${{ needs.setup.outputs.version }}'
          files: |
            .bach/workspace/modules/*.jar

  deploy-api-documentation:
    needs: [ setup, build ]
    if: github.event_name == 'push' && github.repository == 'sormuras/mainrunner' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out pages branch'
        uses: actions/checkout@v2
        with:
          repository: sormuras/api
          token: ${{ secrets.PAT }}
      - name: 'Download build artifact ${{ needs.setup.outputs.version }}'
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ needs.setup.outputs.version }}
      - name: 'Sync early-access documentation'
        run: |
          mkdir --parents mainrunner/early-access
          rsync --archive --delete --verbose .bach/workspace/documentation/api/ mainrunner/early-access
      - name: 'Check for modifications'
        id: diff
        run: |
          git status
          echo ::set-output name=modified::$(if [[ -z $(git status --porcelain) ]]; then echo 'false'; else echo 'true'; fi)
      - name: 'Commit and push changes'
        if: steps.diff.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --message 'Update API documentation of ${{ github.event.repository.name }} ${{ needs.setup.outputs.version }}'
          git push
