name: CI
on: push
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Setup JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11     
      - name: 'Build mainrunner'
        run: jshell build.jsh
